INSERT INTO effect_tag (name) VALUES
                                  ('ATK/DEF Modification'),
                                  ('Activation Condition/Trigger'),
                                  ('Banish'),
                                  ('Battle Manipulation'),
                                  ('Change Battle Position'),
                                  ('Control Change'),
                                  ('Counters'),
                                  ('Destruction'),
                                  ('Draw'),
                                  ('Equip'),
                                  ('Extra Deck Summoning'),
                                  ('Graveyard Effect'),
                                  ('LP Cost'),
                                  ('LP Damage'),
                                  ('LP Healing'),
                                  ('Level/Rank/Attribute Manipulation'),
                                  ('Negation'),
                                  ('Non-Targeting Removal'),
                                  ('Normal Summon Modification'),
                                  ('Piercing Damage'),
                                  ('Protection (Destruction)'),
                                  ('Protection (Targeting)'),
                                  ('Recovery (Hand)'),
                                  ('Restrictions'),
                                  ('Return to Deck (Spinning)'),
                                  ('Return to Hand (Bouncing)'),
                                  ('Search'),
                                  ('Send to GY'),
                                  ('Special Summon (Generic)'),
                                  ('Special Summon (from Banished)'),
                                  ('Special Summon (from Deck)'),
                                  ('Special Summon (from GY)'),
                                  ('Special Summon (from Hand)'),
                                  ('Targeting'),
                                  ('Token Generation'),
                                  ('Tributing'),
                                  ('Unaffected by Effects');
